controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    slider_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_broadcaster:
  ros__parameters:
    use_local_topics: true

slider_position_controller:
  ros__parameters:
    joints:
      - slider_to_camera
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
