<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="base" params="length width height mass">
        <link name="world" />

        <link name="base_link">
            <visual>
                <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
                <material name="orange">
                    <color rgba="1.0 0.3 0.0 1.0"/>
                </material>
            </visual>

            <collision>
                <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <inertia ixx="${(1/12) * mass * ((width  * width)  + (height * height))}" ixy="0.0" ixz="0.0" iyy="${(1/12) * mass * ((length * length) + (height * height))}" iyz="0.0" izz="${(1/12) * mass * ((length * length) + (width  * width))}"/>
            </inertial>
        </link>

        <gazebo reference="base_link">
            <visual>
                <material>
                    <ambient>0.8392 0.6314 0.0 1.0</ambient>
                    <diffuse>0.8392 0.6314 0.0 1.0</diffuse>
                    <specular>0.99 0.99 0.99 1.0</specular>
                    <emissive>0.0 0.0 0.0 0.0</emissive>
                </material>
            </visual>
        </gazebo>

        <joint name="world_to_base" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 0" />
            <parent link="world" />
            <child link="base_link" />
        </joint>

    </xacro:macro>

</robot>